# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GuiParameters")

model_instance <- GuiParameters$new()

test_that("selectedTab", {
  # tests for the property `selectedTab` (character)
  # Selected Result ab.

  # uncomment below to test the property
  #expect_equal(model.instance$`selectedTab`, "EXPECTED_RESULT")
})

test_that("cid", {
  # tests for the property `cid` (character)
  # ID of Selected compound.

  # uncomment below to test the property
  #expect_equal(model.instance$`cid`, "EXPECTED_RESULT")
})

test_that("fid", {
  # tests for the property `fid` (character)
  # ID of Selected Formula candidate of the selected compound.

  # uncomment below to test the property
  #expect_equal(model.instance$`fid`, "EXPECTED_RESULT")
})

test_that("structureCandidateInChIKey", {
  # tests for the property `structureCandidateInChIKey` (character)
  # InChIKey of selected structure candidate of selected formula candidate.

  # uncomment below to test the property
  #expect_equal(model.instance$`structureCandidateInChIKey`, "EXPECTED_RESULT")
})

test_that("bringToFront", {
  # tests for the property `bringToFront` (character)
  # If true bring SIRIUS GUI window to foreground.

  # uncomment below to test the property
  #expect_equal(model.instance$`bringToFront`, "EXPECTED_RESULT")
})
