# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LossEdge")

model_instance <- LossEdge$new()

test_that("sourceFragment", {
  # tests for the property `sourceFragment` (FragmentNode)

  # uncomment below to test the property
  #expect_equal(model.instance$`sourceFragment`, "EXPECTED_RESULT")
})

test_that("targetFragment", {
  # tests for the property `targetFragment` (FragmentNode)

  # uncomment below to test the property
  #expect_equal(model.instance$`targetFragment`, "EXPECTED_RESULT")
})

test_that("molecularFormula", {
  # tests for the property `molecularFormula` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`molecularFormula`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})
