# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ZodiacRunInTwoSteps")

model_instance <- ZodiacRunInTwoSteps$new()

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("identifier", {
  # tests for the property `identifier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`identifier`, "EXPECTED_RESULT")
})
