# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ComputationsApi")

api_instance <- ComputationsApi$new()
data <- "/home/runner/work/sirius-client-openAPI/sirius-client-openAPI/.updater/examples/ms/Kaempferol.ms"
ps_api <- ProjectSpacesApi$new()
compounds_api <- CompoundsApi$new()

test_that("DeleteJob", {
  # tests for DeleteJob
  # base path: http://localhost:8080
  # Delete job.
  # Delete job. Specify how to behave for running jobs.
  # @param project_id character project-space to run jobs on
  # @param job_id character of the job to be deleted
  # @param cancel_if_running character If true job will be canceled if it is not finished. Otherwise,                         deletion will fail for running jobs or request will block until job has finished. (optional)
  # @param await_deletion character If true request will block until deletion succeeded or failed.                         If the job is still running the request will wait until the job has finished. (optional)
  # @return [Void]

  pid <- "computations1"
  dir <- "./computationsDir1"
  ps_api$CreateProjectSpace(pid, dir)
    
  job <- compounds_api$ImportCompounds(pid, data)
  resp <- api_instance$DeleteJobWithHttpInfo(pid, job$id, TRUE, TRUE)
  
  expect_equal(resp$status_code, 202)
    
  compounds_api$DeleteCompound(pid, "1_Kaempferol_Kaempferol")
  ps_api$CloseProjectSpace(pid)
  unlink(dir, recursive = TRUE)  
})

test_that("DeleteJobConfig", {
  # tests for DeleteJobConfig
  # base path: http://localhost:8080
  # Delete job configuration with given name.
  # Delete job configuration with given name.
  # @param name character name of the job-config to delete
  # @return [Void]

  pid <- "computations2"
  dir <- "./computationsDir2"
  ps_api$CreateProjectSpace(pid, dir)
  
  sub <- JobSubmission$new(canopusParas = Canopus$new(enabled=FALSE))
  api_instance$PostJobConfig("canopusConfig", sub)
  resp <- api_instance$GetJobConfig("canopusConfig")
  
  expect_equal(resp$canopusParas$enabled, FALSE)
  
  api_instance$DeleteJobConfig("canopusConfig")
  resp <- api_instance$GetJobConfig("canopusConfig")
  
  expect_equal(resp$status_code, 404)
  
  ps_api$CloseProjectSpace(pid)
  unlink(dir, recursive = TRUE) 
})

test_that("GetDefaultJobConfig", {
  # tests for GetDefaultJobConfig
  # base path: http://localhost:8080
  # Request default job configuration
  # Request default job configuration
  # @param include_config_map character if true, generic configmap with-defaults will be included (optional)
  # @return [JobSubmission]

  pid <- "computations3"
  dir <- "./computationsDir3"
  ps_api$CreateProjectSpace(pid, dir)
    
  compounds_api$ImportCompounds(pid, data)
  resp <- api_instance$GetDefaultJobConfig()
  
  expect_equal(is.logical(resp$recompute), TRUE)
    
  compounds_api$DeleteCompound(pid, "1_Kaempferol_Kaempferol")
  ps_api$CloseProjectSpace(pid)
  unlink(dir, recursive = TRUE) 
})

test_that("GetJob", {
  # tests for GetJob
  # base path: http://localhost:8080
  # Get job information and its current state and progress (if available).
  # Get job information and its current state and progress (if available).
  # @param project_id character project-space to run jobs on
  # @param job_id character of the job to be returned
  # @param include_state character include {@link de.unijena.bioinf.ms.middleware.compute.model.JobProgress de.unijena.bioinf.ms.middleware.compute.model.JobProgress} state. (optional)
  # @param include_command character include job command. (optional)
  # @param include_affected_compounds character include list of compound ids affected by this job (if available) (optional)
  # @return [JobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetJobConfig", {
  # tests for GetJobConfig
  # base path: http://localhost:8080
  # Request job configuration with given name.
  # Request job configuration with given name.
  # @param name character name of the job-config to return
  # @param include_config_map character if true the generic configmap will be part of the output (optional)
  # @return [JobSubmission]

  pid <- "computations5"
  dir <- "./computationsDir5"
  ps_api$CreateProjectSpace(pid, dir)
  
  sub <- JobSubmission$new(fallbackAdducts = c("[M+H]+","[M]+"))
  api_instance$PostJobConfig("adductConfig", sub)
  resp <- api_instance$GetJobConfig("adductConfig")
  
  expect_equal(is.list(resp$fallbackAdducts), TRUE)
  
  api_instance$DeleteJobConfig("adductConfig") 
  ps_api$CloseProjectSpace(pid)
  unlink(dir, recursive = TRUE)
})

test_that("GetJobConfigs", {
  # tests for GetJobConfigs
  # base path: http://localhost:8080
  # Request all available job configurations
  # Request all available job configurations
  # @param include_config_map character if true the generic configmap will be part of the output (optional)
  # @return [array[JobSubmission]]

  pid <- "computations6"
  dir <- "./computationsDir6"
  ps_api$CreateProjectSpace(pid, dir)
  
  sub <- JobSubmission$new()
  api_instance$PostJobConfig("emptyConfig", sub)
  resp <- api_instance$GetJobConfigs()
  
  expect_equal(is.list(resp), TRUE)
  
  api_instance$DeleteJobConfig("emptyConfig") 
  ps_api$CloseProjectSpace(pid)
  unlink(dir, recursive = TRUE)
})

test_that("GetJobs", {
  # tests for GetJobs
  # base path: http://localhost:8080
  # Get job information and its current state and progress (if available).
  # Get job information and its current state and progress (if available).
  # @param project_id character project-space to run jobs on
  # @param include_state character include {@link de.unijena.bioinf.ms.middleware.compute.model.JobProgress de.unijena.bioinf.ms.middleware.compute.model.JobProgress} states. (optional)
  # @param include_command character include job commands. (optional)
  # @param include_affected_compounds character include list of compound ids affected by this job (if available) (optional)
  # @return [array[JobId]]

  pid <- "computations7"
  dir <- "./computationsDir7"
  ps_api$CreateProjectSpace(pid, dir)
  
  resp <- api_instance$GetJobsWithHttpInfo(pid)
  
  expect_equal(is.null(resp$response), FALSE)
  expect_equal(resp$status_code, 200)
  
  ps_api$CloseProjectSpace(pid)
  unlink(dir, recursive = TRUE)
})

test_that("PostJobConfig", {
  # tests for PostJobConfig
  # base path: http://localhost:8080
  # Add new job configuration with given name.
  # Add new job configuration with given name.
  # @param name character name of the job-config to add
  # @param job_submission JobSubmission to add
  # @param override_existing character  (optional)
  # @return [character]

  pid <- "computations8"
  dir <- "./computationsDir8"
  ps_api$CreateProjectSpace(pid, dir)
  
  sub <- JobSubmission$new(zodiacParas = Zodiac$new(enabled=FALSE))
  api_instance$PostJobConfig("zodiacConfig", sub)
  resp <- api_instance$GetJobConfig("zodiacConfig")
  
  expect_equal(resp$zodiacParas$enabled, FALSE)
  
  api_instance$DeleteJobConfig("zodiacConfig") 
  ps_api$CloseProjectSpace(pid)
  unlink(dir, recursive = TRUE)
})

test_that("StartJob", {
  # tests for StartJob
  # base path: http://localhost:8080
  # Start computation for given compounds and with given parameters.
  # Start computation for given compounds and with given parameters.
  # @param project_id character project-space to run jobs on
  # @param job_submission JobSubmission configuration of the job that will be submitted of the job to be returned
  # @param include_state character include {@link de.unijena.bioinf.ms.middleware.compute.model.JobProgress de.unijena.bioinf.ms.middleware.compute.model.JobProgress} state. (optional)
  # @param include_command character include job command. (optional)
  # @param include_affected_compounds character include list of compound ids affected by this job (if available) (optional)
  # @return [JobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("StartJobFromConfig", {
  # tests for StartJobFromConfig
  # base path: http://localhost:8080
  # Start computation for given compounds and with parameters from a stored job-config.
  # Start computation for given compounds and with parameters from a stored job-config.
  # @param project_id character project-space to run jobs on
  # @param job_config_name character name if the config to be used
  # @param request_body array[character] compound ids to be computed
  # @param recompute character enable or disable recompute. If null the stored value will be used. (optional)
  # @param include_state character include {@link de.unijena.bioinf.ms.middleware.compute.model.JobProgress de.unijena.bioinf.ms.middleware.compute.model.JobProgress} state. (optional)
  # @param include_command character include job command. (optional)
  # @param include_affected_compounds character include list of compound ids affected by this job (if available) (optional)
  # @return [JobId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
