# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProjectsApi")

api_instance <- ProjectsApi$new()
path_to_demo_data <- paste(Sys.getenv("HOME"), "sirius-client-openAPI/.updater/clientTests/Data", sep="/")
preproc_ms2_file_1 = paste(path_to_demo_data, "Kaempferol.ms", sep="/")
preproc_ms2_file_2 = paste(path_to_demo_data, "laudanosine.mgf", sep="/")
full_ms_file = paste(path_to_demo_data, "SPF4_Eso3_GH6_01_22643.mzXML", sep="/")


test_that("CloseProjectSpace", {
  # tests for CloseProjectSpace
  # base path: http://localhost:8080
  # Close project-space and remove it from application
  # Close project-space and remove it from application. Project will NOT be deleted from disk.  &lt;p&gt;  ATTENTION: This will cancel and remove all jobs running on this Project before closing it.  If there are many jobs, this might take some time.
  # @param project_id character unique name/identifier of the  project-space to be closed.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CopyProjectSpace", {
  # tests for CopyProjectSpace
  # base path: http://localhost:8080
  # Move an existing (opened) project-space to another location.
  # Move an existing (opened) project-space to another location.
  # @param project_id character unique name/identifier of the project-space that shall be copied.
  # @param path_to_copied_project character target location where the source project will be copied to.
  # @param copy_project_id character optional id/mame of the newly created project (copy). If given the project will be opened. (optional)
  # @param opt_fields array[ProjectInfoOptField]  (optional)
  # @return [ProjectInfo]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateProjectSpace", {
  # tests for CreateProjectSpace
  # base path: http://localhost:8080
  # Create and open a new project-space at given location and make it accessible via the given projectId.
  # Create and open a new project-space at given location and make it accessible via the given projectId.
  # @param project_id character unique name/identifier that shall be used to access the newly created project-space. Must consist only of [a-zA-Z0-9_-].
  # @param path_to_project character local file path where the project will be created. If NULL, project will be stored by its projectId in default project location. DEPRECATED: This parameter relies on the local filesystem and will likely be removed in later versions of this API to allow for more flexible use cases. (optional)
  # @return [ProjectInfo]

  project_id <- "CreateProjectSpace"
  project_dir <- paste(Sys.getenv("HOME"), "CreateProjectSpace", sep="/")

  response <- api_instance$CreateProjectSpace(project_id, project_dir)
  expect_true(inherits(response, "ProjectInfo"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
  withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("GetCanopusClassyFireData", {
  # tests for GetCanopusClassyFireData
  # base path: http://localhost:8080
  # Get CANOPUS prediction vector definition for ClassyFire classes
  # @param project_id character
  # @param charge integer
  # @return [character]

  project_id <- "GetCanopusClassyFireData"
  project_dir <- paste(Sys.getenv("HOME"), "s6TomatoFullAPI", sep="/")
  api_instance$OpenProjectSpace(project_id, project_dir)

  response <- api_instance$GetCanopusClassyFireData(project_id, 56)
  expect_true(inherits(response, "character"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
  # withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("GetCanopusNpcData", {
  # tests for GetCanopusNpcData
  # base path: http://localhost:8080
  # Get CANOPUS prediction vector definition for NPC classes
  # @param project_id character
  # @param charge integer
  # @return [character]

  project_id <- "GetCanopusNpcData"
  project_dir <- paste(Sys.getenv("HOME"), "s6TomatoFullAPI", sep="/")
  api_instance$OpenProjectSpace(project_id, project_dir)

  response <- api_instance$GetCanopusNpcData(project_id, 56)
  expect_true(inherits(response, "character"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
  # withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("GetFingerIdData", {
  # tests for GetFingerIdData
  # base path: http://localhost:8080
  # Get CSI:FingerID fingerprint (prediction vector) definition
  # @param project_id character
  # @param charge integer
  # @return [character]

  project_id <- "GetFingerIdData"
  project_dir <- paste(Sys.getenv("HOME"), "s6TomatoFullAPI", sep="/")
  api_instance$OpenProjectSpace(project_id, project_dir)

  response <- api_instance$GetFingerIdData(project_id, 56)
  expect_true(inherits(response, "character"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
  # withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("GetProjectSpace", {
  # tests for GetProjectSpace
  # base path: http://localhost:8080
  # Get project space info by its projectId.
  # Get project space info by its projectId.
  # @param project_id character unique name/identifier tof the project-space to be accessed.
  # @param opt_fields array[ProjectInfoOptField]  (optional)
  # @return [ProjectInfo]

  project_id <- "GetProjectSpace"
  project_dir <- paste(Sys.getenv("HOME"), "GetProjectSpace", sep="/")
  api_instance$CreateProjectSpace(project_id, project_dir)

  response <- api_instance$GetProjectSpace(project_id)
  expect_true(inherits(response, "ProjectInfo"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
  withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("GetProjectSpaces", {
  # tests for GetProjectSpaces
  # base path: http://localhost:8080
  # List opened project spaces.
  # List opened project spaces.
  # @return [array[ProjectInfo]]

  project_id <- "GetProjectSpaces"
  project_dir <- paste(Sys.getenv("HOME"), "GetProjectSpaces", sep="/")
  api_instance$CreateProjectSpace(project_id, project_dir)

  response <- api_instance$GetProjectSpaces()
  expect_true(inherits(response, "list"))
  expect_true(inherits(response[[1]], "ProjectInfo"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
  withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("ImportMsRunData", {
  # tests for ImportMsRunData
  # base path: http://localhost:8080
  # Import and Align full MS-Runs from various formats into the specified project  Possible formats (mzML, mzXML)
  # Import and Align full MS-Runs from various formats into the specified project  Possible formats (mzML, mzXML)
  # @param project_id character project-space to import into.
  # @param align_runs character  (optional)
  # @param allow_ms1_only character  (optional)
  # @param input_files array[data.frame]  (optional)
  # @return [ImportResult]

  # # TODO LCMS import not implemented
  # project_id <- "ImportMsRunData"
  # project_dir <- paste(Sys.getenv("HOME"), "ImportMsRunData", sep="/")
  # api_instance$CreateProjectSpace(project_id, project_dir)

  # var_input_files <- full_ms_file
  # response <- api_instance$ImportMsRunData(project_id, input_files=var_input_files)
  # expect_true(inherits(response, "ImportResult"))

  # withr::defer(api_instance$CloseProjectSpace(project_id))
  # withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("ImportMsRunDataAsJob", {
  # tests for ImportMsRunDataAsJob
  # base path: http://localhost:8080
  # Import and Align full MS-Runs from various formats into the specified project as background job.
  # Import and Align full MS-Runs from various formats into the specified project as background job.  Possible formats (mzML, mzXML)
  # @param project_id character project-space to import into.
  # @param align_runs character  (optional)
  # @param allow_ms1_only character  (optional)
  # @param opt_fields array[JobOptField] set of optional fields to be included. Use 'none' only to override defaults. (optional)
  # @param input_files array[data.frame]  (optional)
  # @return [Job]

  # # TODO LCMS import not implemented
  # project_id <- "ImportMsRunDataAsJob"
  # project_dir <- paste(Sys.getenv("HOME"), "ImportMsRunDataAsJob", sep="/")
  # api_instance$CreateProjectSpace(project_id, project_dir)

  # var_input_files <- full_ms_file
  # response <- api_instance$ImportMsRunDataAsJob(project_id, input_files=var_input_files)
  # expect_true(inherits(response, "Job"))

  # withr::defer(api_instance$CloseProjectSpace(project_id))
  # withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("ImportPreprocessedData", {
  # tests for ImportPreprocessedData
  # base path: http://localhost:8080
  # Import already preprocessed ms/ms data from various formats into the specified project  Possible formats (ms, mgf, cef, msp)
  # Import already preprocessed ms/ms data from various formats into the specified project  Possible formats (ms, mgf, cef, msp)
  # @param project_id character project-space to import into.
  # @param ignore_formulas character  (optional)
  # @param allow_ms1_only character  (optional)
  # @param input_files array[data.frame]  (optional)
  # @return [ImportResult]

  project_id <- "ImportPreprocessedData"
  project_dir <- paste(Sys.getenv("HOME"), "ImportPreprocessedData", sep="/")
  api_instance$CreateProjectSpace(project_id, project_dir)

  var_input_files <- preproc_ms2_file_1
  response <- api_instance$ImportPreprocessedData(project_id, input_files=var_input_files)
  expect_true(inherits(response, "ImportResult"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
  withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("ImportPreprocessedDataAsJob", {
  # tests for ImportPreprocessedDataAsJob
  # base path: http://localhost:8080
  # Import ms/ms data from the given format into the specified project-space as background job.
  # Import ms/ms data from the given format into the specified project-space as background job.  Possible formats (ms, mgf, cef, msp)
  # @param project_id character project-space to import into.
  # @param ignore_formulas character  (optional)
  # @param allow_ms1_only character  (optional)
  # @param opt_fields array[JobOptField] set of optional fields to be included. Use 'none' only to override defaults. (optional)
  # @param imput_files array[data.frame]  (optional)
  # @return [Job]

  project_id <- "ImportPreprocessedDataAsJob"
  project_dir <- paste(Sys.getenv("HOME"), "ImportPreprocessedDataAsJob", sep="/")
  api_instance$CreateProjectSpace(project_id, project_dir)

  var_input_files <- preproc_ms2_file_1
  response <- api_instance$ImportPreprocessedDataAsJob(project_id, input_files=var_input_files)
  expect_true(inherits(response, "Job"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
  withr::defer(unlink(project_dir, recursive=TRUE))
})

test_that("OpenProjectSpace", {
  # tests for OpenProjectSpace
  # base path: http://localhost:8080
  # Open an existing project-space and make it accessible via the given projectId.
  # Open an existing project-space and make it accessible via the given projectId.
  # @param project_id character unique name/identifier that shall be used to access the opened project-space. Must consist only of [a-zA-Z0-9_-].
  # @param path_to_project character local file path to open the project from. If NULL, project will be loaded by it projectId from default project location.  DEPRECATED: This parameter relies on the local filesystem and will likely be removed in later versions of this API to allow for more flexible use cases. (optional)
  # @param opt_fields array[ProjectInfoOptField]  (optional)
  # @return [ProjectInfo]

  project_id <- "OpenProjectSpace"
  project_dir <- paste(Sys.getenv("HOME"), "s6TomatoFullAPI", sep="/")

  response <- api_instance$OpenProjectSpace(project_id, project_dir)
  expect_true(inherits(response, "ProjectInfo"))

  withr::defer(api_instance$CloseProjectSpace(project_id))
})
