/* 
 * SIRIUS Nightsky API
 *
 * REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.
 *
 * OpenAPI spec version: v0.9 on SIRIUS 5.6.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CanopusPredictions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CanopusPredictionsTests
    {
        // TODO uncomment below to declare an instance variable for CanopusPredictions
        //private CanopusPredictions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CanopusPredictions
            //instance = new CanopusPredictions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CanopusPredictions
        /// </summary>
        [Test]
        public void CanopusPredictionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CanopusPredictions
            //Assert.IsInstanceOfType<CanopusPredictions> (instance, "variable 'instance' is a CanopusPredictions");
        }


        /// <summary>
        /// Test the property 'ClassyFireClasses'
        /// </summary>
        [Test]
        public void ClassyFireClassesTest()
        {
            // TODO unit test for the property 'ClassyFireClasses'
        }
        /// <summary>
        /// Test the property 'NpcClasses'
        /// </summary>
        [Test]
        public void NpcClassesTest()
        {
            // TODO unit test for the property 'NpcClasses'
        }

    }

}
