/* 
 * Sirius Nightsky Middleware API
 *
 * Sirius Nightsky Middleware API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CompoundId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CompoundIdTests
    {
        // TODO uncomment below to declare an instance variable for CompoundId
        //private CompoundId instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CompoundId
            //instance = new CompoundId();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompoundId
        /// </summary>
        [Test]
        public void CompoundIdInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CompoundId
            //Assert.IsInstanceOfType<CompoundId> (instance, "variable 'instance' is a CompoundId");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'IonMass'
        /// </summary>
        [Test]
        public void IonMassTest()
        {
            // TODO unit test for the property 'IonMass'
        }
        /// <summary>
        /// Test the property 'IonType'
        /// </summary>
        [Test]
        public void IonTypeTest()
        {
            // TODO unit test for the property 'IonType'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
