/* 
 * SIRIUS Nightsky API
 *
 * REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.
 *
 * OpenAPI spec version: v0.9 on SIRIUS 5.6.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LossEdge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LossEdgeTests
    {
        // TODO uncomment below to declare an instance variable for LossEdge
        //private LossEdge instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LossEdge
            //instance = new LossEdge();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LossEdge
        /// </summary>
        [Test]
        public void LossEdgeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LossEdge
            //Assert.IsInstanceOfType<LossEdge> (instance, "variable 'instance' is a LossEdge");
        }


        /// <summary>
        /// Test the property 'SourceFragment'
        /// </summary>
        [Test]
        public void SourceFragmentTest()
        {
            // TODO unit test for the property 'SourceFragment'
        }
        /// <summary>
        /// Test the property 'TargetFragment'
        /// </summary>
        [Test]
        public void TargetFragmentTest()
        {
            // TODO unit test for the property 'TargetFragment'
        }
        /// <summary>
        /// Test the property 'MolecularFormula'
        /// </summary>
        [Test]
        public void MolecularFormulaTest()
        {
            // TODO unit test for the property 'MolecularFormula'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

    }

}
