/* 
 * SIRIUS Nightsky API
 *
 * REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.
 *
 * OpenAPI spec version: v0.9 on SIRIUS 5.6.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ResultOverview
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResultOverviewTests
    {
        // TODO uncomment below to declare an instance variable for ResultOverview
        //private ResultOverview instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResultOverview
            //instance = new ResultOverview();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResultOverview
        /// </summary>
        [Test]
        public void ResultOverviewInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResultOverview
            //Assert.IsInstanceOfType<ResultOverview> (instance, "variable 'instance' is a ResultOverview");
        }


        /// <summary>
        /// Test the property 'SiriusScore'
        /// </summary>
        [Test]
        public void SiriusScoreTest()
        {
            // TODO unit test for the property 'SiriusScore'
        }
        /// <summary>
        /// Test the property 'ZodiacScore'
        /// </summary>
        [Test]
        public void ZodiacScoreTest()
        {
            // TODO unit test for the property 'ZodiacScore'
        }
        /// <summary>
        /// Test the property 'TopCSIScore'
        /// </summary>
        [Test]
        public void TopCSIScoreTest()
        {
            // TODO unit test for the property 'TopCSIScore'
        }
        /// <summary>
        /// Test the property 'ConfidenceScore'
        /// </summary>
        [Test]
        public void ConfidenceScoreTest()
        {
            // TODO unit test for the property 'ConfidenceScore'
        }
        /// <summary>
        /// Test the property 'CanopusResult'
        /// </summary>
        [Test]
        public void CanopusResultTest()
        {
            // TODO unit test for the property 'CanopusResult'
        }

    }

}
