# SIRIUS Nightsky API
#
# REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.
#
# OpenAPI spec version: v0.9 on SIRIUS 5.6.1-SNAPSHOT
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' LossEdge Class
#'
#' @field sourceFragment 
#' @field targetFragment 
#' @field molecularFormula 
#' @field score 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LossEdge <- R6::R6Class(
  'LossEdge',
  public = list(
    `sourceFragment` = NULL,
    `targetFragment` = NULL,
    `molecularFormula` = NULL,
    `score` = NULL,
    initialize = function(`sourceFragment`, `targetFragment`, `molecularFormula`, `score`){
      if (!missing(`sourceFragment`)) {
        stopifnot(R6::is.R6(`sourceFragment`))
        self$`sourceFragment` <- `sourceFragment`
      }
      if (!missing(`targetFragment`)) {
        stopifnot(R6::is.R6(`targetFragment`))
        self$`targetFragment` <- `targetFragment`
      }
      if (!missing(`molecularFormula`)) {
        stopifnot(is.character(`molecularFormula`), length(`molecularFormula`) == 1)
        self$`molecularFormula` <- `molecularFormula`
      }
      if (!missing(`score`)) {
        stopifnot(is.numeric(`score`), length(`score`) == 1)
        self$`score` <- `score`
      }
    },
    toJSON = function() {
      LossEdgeObject <- list()
      if (!is.null(self$`sourceFragment`)) {
        LossEdgeObject[['sourceFragment']] <- self$`sourceFragment`$toJSON()
      }
      if (!is.null(self$`targetFragment`)) {
        LossEdgeObject[['targetFragment']] <- self$`targetFragment`$toJSON()
      }
      if (!is.null(self$`molecularFormula`)) {
        LossEdgeObject[['molecularFormula']] <- self$`molecularFormula`
      }
      if (!is.null(self$`score`)) {
        LossEdgeObject[['score']] <- self$`score`
      }

      LossEdgeObject
    },
    fromJSON = function(LossEdgeJson) {
      LossEdgeObject <- jsonlite::fromJSON(LossEdgeJson)
      if (!is.null(LossEdgeObject$`sourceFragment`)) {
        sourceFragmentObject <- FragmentNode$new()
        sourceFragmentObject$fromJSON(jsonlite::toJSON(LossEdgeObject$sourceFragment, auto_unbox = TRUE))
        self$`sourceFragment` <- sourceFragmentObject
      }
      if (!is.null(LossEdgeObject$`targetFragment`)) {
        targetFragmentObject <- FragmentNode$new()
        targetFragmentObject$fromJSON(jsonlite::toJSON(LossEdgeObject$targetFragment, auto_unbox = TRUE))
        self$`targetFragment` <- targetFragmentObject
      }
      if (!is.null(LossEdgeObject$`molecularFormula`)) {
        self$`molecularFormula` <- LossEdgeObject$`molecularFormula`
      }
      if (!is.null(LossEdgeObject$`score`)) {
        self$`score` <- LossEdgeObject$`score`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "sourceFragment": %s,
           "targetFragment": %s,
           "molecularFormula": %s,
           "score": %d
        }',
        self$`sourceFragment`$toJSON(),
        self$`targetFragment`$toJSON(),
        self$`molecularFormula`,
        self$`score`
      )
    },
    fromJSONString = function(LossEdgeJson) {
      LossEdgeObject <- jsonlite::fromJSON(LossEdgeJson)
      FragmentNodeObject <- FragmentNode$new()
      self$`sourceFragment` <- FragmentNodeObject$fromJSON(jsonlite::toJSON(LossEdgeObject$sourceFragment, auto_unbox = TRUE))
      FragmentNodeObject <- FragmentNode$new()
      self$`targetFragment` <- FragmentNodeObject$fromJSON(jsonlite::toJSON(LossEdgeObject$targetFragment, auto_unbox = TRUE))
      self$`molecularFormula` <- LossEdgeObject$`molecularFormula`
      self$`score` <- LossEdgeObject$`score`
    }
  )
)
