# coding: utf-8

"""
    SIRIUS Nightsky API

    REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.  # noqa: E501

    OpenAPI spec version: v0.9 on SIRIUS 5.6.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.zodiac import Zodiac  # noqa: E501
from swagger_client.rest import ApiException


class TestZodiac(unittest.TestCase):
    """Zodiac unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZodiac(self):
        """Test Zodiac"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.zodiac.Zodiac()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
