# coding: utf-8

"""
    Sirius Nightsky Middleware API

    Sirius Nightsky Middleware API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.collision_energy import CollisionEnergy  # noqa: E501
from swagger_client.rest import ApiException


class TestCollisionEnergy(unittest.TestCase):
    """CollisionEnergy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollisionEnergy(self):
        """Test CollisionEnergy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.collision_energy.CollisionEnergy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
