# coding: utf-8

"""
    SIRIUS Nightsky API

    REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.This API is exposed by SIRIUS 6.0.0-SNAPSHOT

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PySirius.api.experimental_gui_api import ExperimentalGUIApi


class TestExperimentalGUIApi(unittest.TestCase):
    """ExperimentalGUIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExperimentalGUIApi()

    def tearDown(self) -> None:
        pass

    def test_apply_to_gui(self) -> None:
        """Test case for apply_to_gui

        Apply given changes to the running GUI instance.
        """
        pass

    def test_close_gui(self) -> None:
        """Test case for close_gui

        Close GUI instance of given project-space if available.
        """
        pass

    def test_get_guis(self) -> None:
        """Test case for get_guis

        Get list of currently running gui windows, managed by this SIRIUS instance.
        """
        pass

    def test_open_gui(self) -> None:
        """Test case for open_gui

        Open GUI instance on specified project-space and bring the GUI window to foreground.
        """
        pass


if __name__ == '__main__':
    unittest.main()