=begin
#Sirius Nightsky Middleware API

#Sirius Nightsky Middleware API

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'date'

module SwaggerClient
  class File
    attr_accessor :absolute

    attr_accessor :absolute_file

    attr_accessor :absolute_path

    attr_accessor :canonical_file

    attr_accessor :canonical_path

    attr_accessor :directory

    attr_accessor :file

    attr_accessor :free_space

    attr_accessor :hidden

    attr_accessor :name

    attr_accessor :parent

    attr_accessor :parent_file

    attr_accessor :path

    attr_accessor :total_space

    attr_accessor :usable_space

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'absolute' => :'absolute',
        :'absolute_file' => :'absoluteFile',
        :'absolute_path' => :'absolutePath',
        :'canonical_file' => :'canonicalFile',
        :'canonical_path' => :'canonicalPath',
        :'directory' => :'directory',
        :'file' => :'file',
        :'free_space' => :'freeSpace',
        :'hidden' => :'hidden',
        :'name' => :'name',
        :'parent' => :'parent',
        :'parent_file' => :'parentFile',
        :'path' => :'path',
        :'total_space' => :'totalSpace',
        :'usable_space' => :'usableSpace'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'absolute' => :'BOOLEAN',
        :'absolute_file' => :'File',
        :'absolute_path' => :'String',
        :'canonical_file' => :'File',
        :'canonical_path' => :'String',
        :'directory' => :'BOOLEAN',
        :'file' => :'BOOLEAN',
        :'free_space' => :'Integer',
        :'hidden' => :'BOOLEAN',
        :'name' => :'String',
        :'parent' => :'String',
        :'parent_file' => :'File',
        :'path' => :'String',
        :'total_space' => :'Integer',
        :'usable_space' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'absolute')
        self.absolute = attributes[:'absolute']
      end

      if attributes.has_key?(:'absoluteFile')
        self.absolute_file = attributes[:'absoluteFile']
      end

      if attributes.has_key?(:'absolutePath')
        self.absolute_path = attributes[:'absolutePath']
      end

      if attributes.has_key?(:'canonicalFile')
        self.canonical_file = attributes[:'canonicalFile']
      end

      if attributes.has_key?(:'canonicalPath')
        self.canonical_path = attributes[:'canonicalPath']
      end

      if attributes.has_key?(:'directory')
        self.directory = attributes[:'directory']
      end

      if attributes.has_key?(:'file')
        self.file = attributes[:'file']
      end

      if attributes.has_key?(:'freeSpace')
        self.free_space = attributes[:'freeSpace']
      end

      if attributes.has_key?(:'hidden')
        self.hidden = attributes[:'hidden']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'parent')
        self.parent = attributes[:'parent']
      end

      if attributes.has_key?(:'parentFile')
        self.parent_file = attributes[:'parentFile']
      end

      if attributes.has_key?(:'path')
        self.path = attributes[:'path']
      end

      if attributes.has_key?(:'totalSpace')
        self.total_space = attributes[:'totalSpace']
      end

      if attributes.has_key?(:'usableSpace')
        self.usable_space = attributes[:'usableSpace']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          absolute == o.absolute &&
          absolute_file == o.absolute_file &&
          absolute_path == o.absolute_path &&
          canonical_file == o.canonical_file &&
          canonical_path == o.canonical_path &&
          directory == o.directory &&
          file == o.file &&
          free_space == o.free_space &&
          hidden == o.hidden &&
          name == o.name &&
          parent == o.parent &&
          parent_file == o.parent_file &&
          path == o.path &&
          total_space == o.total_space &&
          usable_space == o.usable_space
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [absolute, absolute_file, absolute_path, canonical_file, canonical_path, directory, file, free_space, hidden, name, parent, parent_file, path, total_space, usable_space].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
