# Sirius Nightsky Middleware API
#
# Sirius Nightsky Middleware API
#
# OpenAPI spec version: 1.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' @title CompoundController operations
#' @description swagger.CompoundController
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' get_compound_ids_using_get getCompoundIds
#'
#'
#' get_compound_using_get getCompound
#'
#' }
#'
#' @export
CompoundControllerApi <- R6::R6Class(
  'CompoundControllerApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    get_compound_ids_using_get = function(pid, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/api/projects/{pid}/compounds"
      if (!missing(`pid`)) {
        urlPath <- gsub(paste0("\\{", "pid", "\\}"), `pid`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- CompoundId$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    get_compound_using_get = function(cid, pid, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/api/projects/{pid}/compounds/{cid}"
      if (!missing(`cid`)) {
        urlPath <- gsub(paste0("\\{", "cid", "\\}"), `cid`, urlPath)
      }

      if (!missing(`pid`)) {
        urlPath <- gsub(paste0("\\{", "pid", "\\}"), `pid`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- CompoundMsData$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
