/* 
 * SIRIUS Nightsky API
 *
 * REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.
 *
 * OpenAPI spec version: v0.9 on SIRIUS 5.6.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Deviation
    /// </summary>
    [DataContract]
        public partial class Deviation :  IEquatable<Deviation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Deviation" /> class.
        /// </summary>
        /// <param name="ppm">ppm.</param>
        /// <param name="absolute">absolute.</param>
        /// <param name="identifier">identifier.</param>
        public Deviation(double? ppm = default(double?), double? absolute = default(double?), string identifier = default(string))
        {
            this.Ppm = ppm;
            this.Absolute = absolute;
            this.Identifier = identifier;
        }
        
        /// <summary>
        /// Gets or Sets Ppm
        /// </summary>
        [DataMember(Name="ppm", EmitDefaultValue=false)]
        public double? Ppm { get; set; }

        /// <summary>
        /// Gets or Sets Absolute
        /// </summary>
        [DataMember(Name="absolute", EmitDefaultValue=false)]
        public double? Absolute { get; set; }

        /// <summary>
        /// Gets or Sets Identifier
        /// </summary>
        [DataMember(Name="identifier", EmitDefaultValue=false)]
        public string Identifier { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Deviation {\n");
            sb.Append("  Ppm: ").Append(Ppm).Append("\n");
            sb.Append("  Absolute: ").Append(Absolute).Append("\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Deviation);
        }

        /// <summary>
        /// Returns true if Deviation instances are equal
        /// </summary>
        /// <param name="input">Instance of Deviation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Deviation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Ppm == input.Ppm ||
                    (this.Ppm != null &&
                    this.Ppm.Equals(input.Ppm))
                ) && 
                (
                    this.Absolute == input.Absolute ||
                    (this.Absolute != null &&
                    this.Absolute.Equals(input.Absolute))
                ) && 
                (
                    this.Identifier == input.Identifier ||
                    (this.Identifier != null &&
                    this.Identifier.Equals(input.Identifier))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Ppm != null)
                    hashCode = hashCode * 59 + this.Ppm.GetHashCode();
                if (this.Absolute != null)
                    hashCode = hashCode * 59 + this.Absolute.GetHashCode();
                if (this.Identifier != null)
                    hashCode = hashCode * 59 + this.Identifier.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
