/* 
 * SIRIUS Nightsky API
 *
 * REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.
 *
 * OpenAPI spec version: v0.9 on SIRIUS 5.6.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// User/developer friendly parameter subset for the CSI:FingerID Fingerprint tool
    /// </summary>
    [DataContract]
        public partial class FingerprintPrediction :  IEquatable<FingerprintPrediction>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FingerprintPrediction" /> class.
        /// </summary>
        /// <param name="enabled">tags whether the tool is enabled.</param>
        /// <param name="useScoreThreshold">If true, an adaptive soft threshold will be applied to only compute Fingerprints for promising formula candidates  Enabling is highly recommended..</param>
        public FingerprintPrediction(bool? enabled = default(bool?), bool? useScoreThreshold = default(bool?))
        {
            this.Enabled = enabled;
            this.UseScoreThreshold = useScoreThreshold;
        }
        
        /// <summary>
        /// tags whether the tool is enabled
        /// </summary>
        /// <value>tags whether the tool is enabled</value>
        [DataMember(Name="enabled", EmitDefaultValue=false)]
        public bool? Enabled { get; set; }

        /// <summary>
        /// If true, an adaptive soft threshold will be applied to only compute Fingerprints for promising formula candidates  Enabling is highly recommended.
        /// </summary>
        /// <value>If true, an adaptive soft threshold will be applied to only compute Fingerprints for promising formula candidates  Enabling is highly recommended.</value>
        [DataMember(Name="useScoreThreshold", EmitDefaultValue=false)]
        public bool? UseScoreThreshold { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FingerprintPrediction {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  UseScoreThreshold: ").Append(UseScoreThreshold).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FingerprintPrediction);
        }

        /// <summary>
        /// Returns true if FingerprintPrediction instances are equal
        /// </summary>
        /// <param name="input">Instance of FingerprintPrediction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FingerprintPrediction input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Enabled == input.Enabled ||
                    (this.Enabled != null &&
                    this.Enabled.Equals(input.Enabled))
                ) && 
                (
                    this.UseScoreThreshold == input.UseScoreThreshold ||
                    (this.UseScoreThreshold != null &&
                    this.UseScoreThreshold.Equals(input.UseScoreThreshold))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Enabled != null)
                    hashCode = hashCode * 59 + this.Enabled.GetHashCode();
                if (this.UseScoreThreshold != null)
                    hashCode = hashCode * 59 + this.UseScoreThreshold.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
