=begin
#Sirius Nightsky Middleware API

#Sirius Nightsky Middleware API

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/annotated_spectrum'
require 'swagger_client/models/collision_energy'
require 'swagger_client/models/compound_id'
require 'swagger_client/models/compound_ms_data'
require 'swagger_client/models/file'
require 'swagger_client/models/project_space_id'

# APIs
require 'swagger_client/api/compound_controller_api'
require 'swagger_client/api/project_space_controller_api'
require 'swagger_client/api/version_info_controller_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
