# coding: utf-8

"""
    SIRIUS Nightsky API

    REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.This API is exposed by SIRIUS 6.0.0-SNAPSHOT

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from PySirius.models.aligned_feature_opt_field import AlignedFeatureOptField

class TestAlignedFeatureOptField(unittest.TestCase):
    """AlignedFeatureOptField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlignedFeatureOptField(self):
        """Test AlignedFeatureOptField"""
        # inst = AlignedFeatureOptField()

if __name__ == '__main__':
    unittest.main()
