# NOTE: This repository "sirius_client_openapi" has to be the current working directory to run this script.
#       The package 'devtools' has to be installed in order to create the documentation.
#       If this is not the case, run following code: if(!require(devtools)){install.packages("devtools")}

#########################################################################################
### CREATE PACKAGE SKELETON - Create a directory which contains the generated R files ###
#########################################################################################

# Step 1: Create the package directory <package_name> with its subdirectories <package_name>\man and <package_name>\R
package_name <- "Rsirius"

# If there is already a built package, then delete only its contained files.
# If there is not the package, then create its directories.
if(dir.exists(file.path(getwd(),"build",package_name))){
    files_to_remove <- list.files(file.path(getwd(),"build",package_name,c("R","man","")), include.dirs = FALSE, all.files = TRUE, full.names = TRUE)
    file.remove(files_to_remove)
    print(paste("Old files",files_to_remove,"were removed.", sep = " "))
}else{
    dir.create(path = file.path(getwd(),"build",package_name,"R"), recursive = TRUE, showWarnings = TRUE)
    dir.create(file.path(getwd(),"build",package_name,"man"), recursive = FALSE, showWarnings = TRUE)
    print(paste("Directories",file.path(getwd(),"build",package_name),",",file.path(getwd(),"build",package_name,"man"),"and",file.path(getwd(),"build",package_name,"R"),"created."))
}

# Step 2: Copying of all R files, which were generated by Swagger-Codegen, and the R file with the extended ApiClient object.
# assumption: Swagger-Codegen generates R files which contain only one R object.
#             These R objects have the same name as the file in which they are contained.
dir_gen_scripts <- file.path(getwd(),"client_api_r","generated","R")
gen_scripts <- list.files(dir_gen_scripts, all.files = TRUE)
path_gen_scripts <- file.path(dir_gen_scripts,gen_scripts)

files_to_copy <- c(path_gen_scripts,file.path(getwd(),"client_api_r","SiriusApi.R"))
file.copy(from = files_to_copy, to = file.path(getwd(),"build",package_name,"R"))

# The directory with name <package_name> and subdirectories "man" and "R" were created.
# The subdirectory <package_name>\R contains all R files with only one R object.
# These R objects have the same name as the file in which they are contained.

print(paste("Copied all R scripts into",file.path(getwd(),"build",package_name,"R"),"."))

######################################################################################################
### PACKAGE DESCRIPTION AND LICENSE - Copying of the already existing DESCRIPTION and LICENSE file ###
######################################################################################################

files <- file.path(getwd(),"client_api_r",c("DESCRIPTION","LICENSE"))
file.copy(from = files, to = file.path(getwd(),"build",package_name))

print(paste("Copied the DESCRIPTION and LICENSE file into",file.path(getwd(),"build",package_name),"."))

########################################################################
### DOCUMENTATION - Create the .Rd help files and the NAMESPACE file ###
########################################################################

# The .Rd files and the NAMESPACE file can be automatically generated by calling devtools::document
# (or better roxygen2::roxygenize). Each .Rd help file represents the documentation of the respective R object.

# First: load the devtools package
if(!require(devtools)){
    install.packages("devtools")
    require(devtools)
}
# Second: generate the .Rd help files and the NAMESPACE by calling devtools::document
document(pkg = file.path(getwd(),"build",package_name))

print("Created the NAMESPACE file and all .Rd help files.")

# Because roxygen2 does not create a help file for the whole package,
# the <package_name>-package.Rd file has to be copied into the directory <package_name>\man:
file.copy(from = file.path(getwd(),"client_api_r","Rsirius-package.Rd"),to = file.path(getwd(),"build",package_name,"man"))

print("Copied the .Rd help file for the whole R package.")

print("FINISHED WITH CREATING PACKAGE")