=begin
#Sirius Nightsky Middleware API

#Sirius Nightsky Middleware API

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ProjectSpaceControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectSpaceControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ProjectSpaceControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectSpaceControllerApi' do
    it 'should create an instance of ProjectSpaceControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ProjectSpaceControllerApi)
    end
  end

  # unit tests for get_project_space_using_get
  # getProjectSpace
  # @param name name
  # @param [Hash] opts the optional parameters
  # @return [ProjectSpaceId]
  describe 'get_project_space_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_project_spaces_using_get
  # getProjectSpaces
  # @param [Hash] opts the optional parameters
  # @return [Array<ProjectSpaceId>]
  describe 'get_project_spaces_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for open_project_space_using_post
  # openProjectSpace
  # @param path path
  # @param [Hash] opts the optional parameters
  # @return [ProjectSpaceId]
  describe 'open_project_space_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for open_project_space_using_put
  # openProjectSpace
  # @param name name
  # @param path path
  # @param [Hash] opts the optional parameters
  # @return [ProjectSpaceId]
  describe 'open_project_space_using_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
