=begin
#Sirius Nightsky Middleware API

#Sirius Nightsky Middleware API

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::VersionInfoControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VersionInfoControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::VersionInfoControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VersionInfoControllerApi' do
    it 'should create an instance of VersionInfoControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::VersionInfoControllerApi)
    end
  end

  # unit tests for get_version_info_using_get
  # getVersionInfo
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_version_info_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
